# .github/ranger.yaml
    default:
      close:
        # Default time to wait before closing the label. Can either be a number in milliseconds
        # or a string specified by the `ms` package (https://www.npmjs.com/package/ms)
        delay: "3 days"

        # Default comment to post when an issue is first marked with a closing label
        #
        #   $DELAY will automatically be replaced with `delay` as a formatted string (e.g. '7 days')
        #   $LABEL will automatically be replaced with the label's name
        comment: "⚠️ This issue has been marked $LABEL and will be closed in $DELAY".

    # Map from each label name to its configuration
    labels:
      duplicate:
        action: close
        delay: 15s
        comment: "Duplicate issue created! Closing in $DELAY . . ."
      invalid: close # use defaults for comment and delay time
      stale:
        action: close
        delay: 7 days
        comment: false # don't comment anything
      'merge when passing': merge
      approved:
        action: merge
      'new contributor':
        action: comment
        delay: 5s
    	  message: "Thanks for making your first contribution! :slightly_smiling_face:"


    # All maintainer comments containing the pattern "duplicate of"
    # will apply the duplicate label
    comments:
        # As of now `label` is the only valid action that can be triggered by
        # comments, and is a required field
      - action: label
        # either a string or a string representation of a regular expresssion
        pattern: /duplicate of/i
        labels:
          - duplicate
        # delete comments that match a specific pattern. In this case, all comments
        # that include "+1" will be deleted.
      - action: delete_comment
        pattern: "+1" # can also be a regular expression

    # Same as `comments` except Ranger will look in the body of new commits
    # that are pushed to a pull request
    commits:
      - action: label
        pattern: /Merge when passing/i
        labels:
          - merge when passing
