---
title: "Introduction to robvis"
author: "LAM"
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{Introduction to robvis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  fig.width = 8,
  fig.height = 2.41)
  library(tidyverse)
library(robvis)
```
## R Markdown



```{r rob2summary}
#Import data for ROB2.0 based risk-of-bias assessments

# Produce barchart summarising risk of bias for each domain, weighted by study precision.
robvis::rob_summary(robvis::data_rob, tool = "ROB2", save = "No")
```

Users can also produce summary plots for two other commonly used tools: ROBINS-I and QUADAS-2

```{r robinssummary}
#Import data for ROB2.0 based risk-of-bias assessments
# Produce barchart summarising risk of bias for each domain, weighted by study precision.
robvis::rob_summary(data_robins, tool = "ROBINS-I", save = "No")
```

```{r quadassummary}
#Import data for ROB2.0 based risk-of-bias assessments
# Produce barchart summarising risk of bias for each domain, weighted by study precision.
robvis::rob_summary(data_quadas, tool = "QUADAS-2", save = "No")
```
