app <- ShinyDriver$new("../")
app$snapshotInit("navigation")
Sys.sleep(1.5)
app$setInputs(gotoabout = "click")
app$snapshot()
app$setInputs(mytabsetpanel = "data")
Sys.sleep(0.5)
app$snapshot()
app$setInputs(mytabsetpanel = "Home")
Sys.sleep(0.5)
app$snapshot()
app$setInputs(gotodata = "click")
Sys.sleep(0.5)
app$snapshot()
